import type { Metadata } from "next";
import { Inter, Comfortaa, Poppins } from "next/font/google";
import "./globals.css";
import Carrito from "@/components/Carrito";

//const inter = Inter({ subsets: ["latin"] });
const inter = Comfortaa({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Amigurumi ZLEN | Home",
  description: "Generated by CRLS create NextApp",
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Carrito />
      </body>
    </html>
  );
}
