import { createSlice } from "@reduxjs/toolkit";

//const initialState = { amig: 0, carrito:[] };
const initialState = [
  {
    name: "Lindos Nonos Amigurumi",
    image: "abu1.jpg",
    price: 50,
    bgAvatar: "bg-[url('/image/abu1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },

  {
    name: "Animales Grupo #1",
    image: "animales1.jpg",
    price: 25,
    bgAvatar: "bg-[url('/image/animales1.jpg')]",
    inStock: true,
    rating: 3,
    category: "Colecciones",
  },
  {
    name: "Animales Grupo #2",
    image: "animales2.jpg",
    price: 43,
    bgAvatar: "bg-[url('/image/animales2.jpg')]",
    inStock: false,
    rating: 3,
    category: "Colecciones",
  },
  {
    name: "Animales Grupo #3",
    image: "animales3.jpg",
    price: 44,
    bgAvatar: "bg-[url('/image/animales3.jpg')]",
    inStock: true,
    rating: 3,
    category: "Colecciones",
  },
  {
    name: "Animales Grupo #4",
    image: "animales4.jpg",
    price: 30,
    bgAvatar: "bg-[url('/image/animales4.jpg')]",
    inStock: false,
    rating: 3,
    category: "Colecciones",
  },
  {
    name: "Animales Grupo #5",
    image: "animales5.jpg",
    price: 30,
    bgAvatar: "bg-[url('/image/animales5.jpg')]",
    inStock: true,
    rating: 3,
    category: "Colecciones",
  },
  {
    name: "Animales Grupo #6",
    image: "animales6.avif",
    price: 30,
    bgAvatar: "bg-[url('/image/animales6.avif')]",
    inStock: true,
    rating: 3,
    category: "Colecciones",
  },
  {
    name: "Banana Funny Amigurumi",
    image: "banana1.jpg",
    price: 35,
    bgAvatar: "bg-[url('/image/banana1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },
  {
    name: "Beimax Grandes Heroes Amigurumi",
    image: "baymax1.jpg",
    price: 30,
    bgAvatar: "bg-[url('/image/baymax1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animaciones",
  },
  {
    name: "Hash Pokemon Amigurumi",
    image: "boy1.jpg",
    price: 50,
    bgAvatar: "bg-[url('/image/boy1.jpg')]",
    inStock: true,
    rating: 5,
    category: "Animaciones",
  },
  {
    name: "Joven Cool Amigurumi",
    image: "boy2.jpg",
    price: 59,
    bgAvatar: "bg-[url('/image/boy2.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animaciones",
  },
  {
    name: "Captus Baby Amigurumi",
    image: "captus1.jpg",
    price: 25,
    bgAvatar: "bg-[url('/image/captus1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },
  {
    name: "Captus Chibi Amigurumi",
    image: "captus2.jpg",
    price: 35,
    bgAvatar: "bg-[url('/image/captus2.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },
  {
    name: "Captus Amoroso Amigurumi",
    image: "captus3.jpg",
    price: 40,
    bgAvatar: "bg-[url('/image/captus3.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },
  {
    name: "Captus Funny Amigurumi",
    image: "captus4.jpg",
    price: 45,
    bgAvatar: "bg-[url('/image/captus4.jpg')]",
    inStock: true,
    rating: 5,
    category: "Divertidos",
  },
  {
    name: "Chuky Chibi Amigurumi",
    image: "chuky1.jpg",
    price: 55,
    bgAvatar: "bg-[url('/image/chuky1.jpg')]",
    inStock: true,
    rating: 5,
    category: "Animaciones",
  },
  {
    name: "Chuky Boy Amigurumi #2",
    image: "chuky3.jpg",
    price: 65,
    bgAvatar: "bg-[url('/image/chuky3.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animaciones",
  },
  {
    name: "Perro Amigurumi",
    image: "dog1.jpg",
    price: 45,
    bgAvatar: "bg-[url('/image/dog1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Dragon Amigurumi",
    image: "dragon1.jpg",
    price: 75,
    bgAvatar: "bg-[url('/image/dragon1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Dragon Chibi Amigurumi",
    image: "dragon2.jpg",
    price: 85,
    bgAvatar: "bg-[url('/image/dragon2.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Dragon Teal Amigurumi",
    image: "dragon3.jpg",
    price: 75,
    bgAvatar: "bg-[url('/image/dragon3.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Oso Exotic Amigurumi",
    image: "exotic1.png",
    price: 65,
    bgAvatar: "bg-[url('/image/exotic1.png')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Gato Exotic Amigurumi",
    image: "exotic2.jpg",
    price: 85,
    bgAvatar: "bg-[url('/image/exotic2.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Girl Bella Amigurumi",
    image: "girl1.jpg",
    price: 65,
    bgAvatar: "bg-[url('/image/girl1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },
  {
    name: "Girl Con Moños Amigurumi",
    image: "girl2.jpg",
    price: 55,
    bgAvatar: "bg-[url('/image/girl2.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },
  {
    name: "Girl Ballet Amigurumi",
    image: "girl3.jpg",
    price: 50,
    bgAvatar: "bg-[url('/image/girl3.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },
  {
    name: "Bella Bailarina Amigurumi",
    image: "girl4.jpg",
    price: 55,
    bgAvatar: "bg-[url('/image/girl4.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },
  {
    name: "Cabello Largo Amigurumi",
    image: "girl5.jpg",
    price: 45,
    bgAvatar: "bg-[url('/image/girl5.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },
  {
    name: "Girl Primeros Pasos Amigurumi",
    image: "girl6.jpg",
    price: 40,
    bgAvatar: "bg-[url('/image/girl6.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidos",
  },
  {
    name: "Gotic Amigurumi #1",
    image: "gotic1.jpg",
    price: 45,
    bgAvatar: "bg-[url('/image/gotic1.jpg')]",
    inStock: true,
    rating: 3,
    category: "Colecciones",
  },
  {
    name: "Gotic Amigurumi #2",
    image: "gotic2.avif",
    price: 45,
    bgAvatar: "bg-[url('/image/gotic2.avif')]",
    inStock: true,
    rating: 5,
    category: "Colecciones",
  },
  {
    name: "Mono y su Banana Amigurumi #2",
    image: "monky2.jpg",
    price: 45,
    bgAvatar: "bg-[url('/image/monky2.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Oruga Amigurumi",
    image: "oruga1.jpg",
    price: 45,
    bgAvatar: "bg-[url('/image/oruga1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Peluches Amigurumi",
    image: "peluche1.jpg",
    price: 35,
    bgAvatar: "bg-[url('/image/peluche1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Divertidas",
  },
  {
    name: "Pokemones Chibi Amigurumi",
    image: "pokemon1.jpg",
    price: 35,
    bgAvatar: "bg-[url('/image/pokemon1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Colecciones",
  },
  {
    name: "Pokemon Hash Amigurumi",
    image: "pokemon3.jpg",
    price: 35,
    bgAvatar: "bg-[url('/image/pokemon3.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animaciones",
  },
  {
    name: "Pokemon Amigurumi #4",
    image: "pokemon4.jpg",
    price: 45,
    bgAvatar: "bg-[url('/image/pokemon4.jpg')]",
    inStock: true,
    rating: 4,
    category: "Colecciones",
  },
  {
    name: "Giglipo Amigurumi",
    image: "pokemon6.jpg",
    price: 35,
    bgAvatar: "bg-[url('/image/pokemon6.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animaciones",
  },
  {
    name: "Scuero Amigurumi",
    image: "pokemon7.jpg",
    price: 35,
    bgAvatar: "bg-[url('/image/pokemon7.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animaciones",
  },
  {
    name: "Pony Tierno Amigurumi",
    image: "pony1.jpg",
    price: 45,
    bgAvatar: "bg-[url('/image/pony1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Conejo Azul Amigurumi",
    image: "rabbit1.jpg",
    price: 30,
    bgAvatar: "bg-[url('/image/rabbit1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Bella Coneja Amigurumi",
    image: "rabbit2.jpg",
    price: 75,
    bgAvatar: "bg-[url('/image/rabbit2.jpg')]",
    inStock: true,
    rating: 5,
    category: "Animales",
  },
  {
    name: "Conejo de Invierno Amigurumi",
    image: "rabbit3.jpg",
    price: 30,
    bgAvatar: "bg-[url('/image/rabbit3.jpg')]",
    inStock: true,
    rating: 4,
    category: "Colecciones",
  },
  {
    name: "Conejita Amigurumi",
    image: "rabbit4.jpg",
    price: 30,
    bgAvatar: "bg-[url('/image/rabbit4.jpg')]",
    inStock: true,
    rating: 4,
    category: "Colecciones",
  },
  {
    name: "Conejo Chibi Amigurumi",
    image: "rabbit5.jpg",
    price: 30,
    bgAvatar: "bg-[url('/image/rabbit5.jpg')]",
    inStock: true,
    rating: 5,
    category: "Animales",
  },
  {
    name: "Reno Amigurumi",
    image: "reno1.jpg",
    price: 45,
    bgAvatar: "bg-[url('/image/reno1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Unicornio Amigurumi",
    image: "unicornio1.jpg",
    price: 45,
    bgAvatar: "bg-[url('/image/unicornio1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Animales",
  },
  {
    name: "Winnie Pooh Amigurumi #1",
    image: "winniepooh1.jpg",
    price: 30,
    bgAvatar: "bg-[url('/image/winniepooh1.jpg')]",
    inStock: true,
    rating: 4,
    category: "Colecciones",
  },
];

export const productsSlice = createSlice({
  name: "products",
  initialState,
  reducers: {
    listProducts: (state) => state,
    //increment: (state) => {
    //  state.amig += 1;
    //},
    /*filterByCategory: (state, action) => {
      state.filter((item) => item.category === action.payload);
    },
    filterByStock: (state) => state,
    filterByRating: (state) => state,
    filterBySearch: (state) => state, */
  },
});

export const { listProducts } = productsSlice.actions;

export default productsSlice.reducer;
