import type { Metadata } from "next";
import { Inter, Comfortaa, Raleway } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/providers";
import { Header } from "@/components/Header";
import Footer from "@/components/Footer";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { ReactNode } from "react";

//const inter = Inter({ subsets: ["latin"] });
const inter = Comfortaa({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Amigurumi ZLEN | Home",
  description: "Generated by CRLS create NextApp",
  //themeColor: "#000000",
};

type Props = {
  children: ReactNode;
  params: { locale: string };
};

export default function LocaleLayout({ children, params: { locale } }: Props) {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Providers>
            <Header />
            {children}
            <Footer />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
